WebUI/Controllers/InfoController.cs
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using Domain.Repositories;
using WebUI.Models;

namespace WebUI.Controllers
{
  public class InfoController : Controller
  {
    private readonly IVkRepository _vkRepository;

    public InfoController(IVkRepository vkRepository)
    {
      _vkRepository = vkRepository;
    }

    public ActionResult Index()
    {
      var playlists = _vkRepository.GetAllPlayLists();

      var infoModels = new List<InfoModel>();

      var users = playlists.GroupBy(r => r.UserId).Select(r => r.ToList()).ToList();

      foreach (var userPlaylists in users)
      {
        var infoModel = new InfoModel
        {
          UserId = userPlaylists.First().UserId
        };

        var playlistCount = userPlaylists.Count();
        var trackCount = userPlaylists.Sum(r => r.AudioTracks.Count);

        infoModel.PlaylistCount = playlistCount;
        infoModel.TrackCount = trackCount;
        infoModel.Playlists.AddRange(userPlaylists.Select(r => r.Id));

        infoModels.Add(infoModel);
      }

      infoModels = infoModels.OrderByDescending(r => r.TrackCount).Take(500).ToList();

      return View(infoModels);
    }
  }
}

WebUI/Controllers/VkMusicController.cs
using System.Web.Mvc;

namespace WebUI.Controllers
{
  public class VkMusicController : Controller
  {
    public ActionResult Index()
    {
      @ViewBag.sharedId = Session["sharedId"];
      Session["sharedId"] = 0;

      ViewBag.maxTracksCount = WebApiApplication.MaxTracksCount;
      ViewBag.maxPlaylistsCount = WebApiApplication.MaxPlaylistsCount; 
      return View();
    }

    public ActionResult Shared(int? id)
    {     
      Session["sharedId"] = id;
      return RedirectToAction("Index");
    }
  }
}

WebUI/Views/Info/Index.cshtml
@model IEnumerable<WebUI.Models.InfoModel>

@{
  Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/bootstrap")
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>
</head>
<body>

    <div class="col-md-12">
        <a class="btn btn-info" href="@Url.Action("Index", "VkMusic")">Main page</a>

        <hr />
        <div>
            Users: @Model.Count()
            <br />
            Playlists: @Model.Sum(r => r.PlaylistCount)
            <br />
            AudioTracks: @Model.Sum(r => r.TrackCount)
            <br />
        </div>

        <hr />


        <table class="table table-hover">
            <tr class="info">
                <th>
                    User id
                </th>
                <th>
                    Number of playlists
                </th>
                <th>
                    Number of tracks
                </th>
                <th>
                    Playlists
                </th>
            </tr>

            @foreach (var item in Model)
            {
            <tr>
                <td>
                    <a href="@string.Format("https://vk.com/id{0}", Html.DisplayFor(modelItem => item.UserId))" target="_blank">
                        @Html.DisplayFor(modelItem => item.UserId)
                    </a>
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.PlaylistCount)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.TrackCount)
                </td>
                <td>
                    @foreach (var playlist in item.Playlists)
                    {
                      <a href="@string.Format("http://vplayliste.azurewebsites.net/VkMusic/Shared/?id={0}", Html.DisplayFor(modelItem => playlist))" target="_blank">
                        @Html.DisplayFor(modelItem => playlist);
                      </a>
                    }
                </td>
            </tr>
            }

        </table>
    </div>
</body>
</html>